---
- name: Installing all the required packages
  yum:
    name: "{{ item }}"
    state: present
  loop: "{{ pkgs }}"

- name: Creating index.html from ansible jinja2 template
  template:
    src: index.html.j2
    dest: /var/www/html/index.html

- name: Starting and enable service
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop: "{{ pkgs }}" 

- name: Managing firewall rules
  firewalld:
    service: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled        
  loop: "{{ rule }}"