    - name: Get running processes
      ignore_errors: yes
      shell: "ps -ef | grep top | awk '{print $2}'"
      register: running_processes

    - name: kill all processes
      ignore_errors: yes
      shell: "kill {{ item }} "
      with_items: "{{ running_processes.stdout_lines }}"