---
- name: "My First Playbook"
  hosts: ec2
  become_user: root
  become: yes

  tasks:
    - name: Install Apache on Ubuntu server
      apt:
        name: apache2
        state: present
      when: ansible_os_family == 'Ubuntu'

    - name: Install Apache on RedHat server
      yum:
        name: httpd
        state: present
      when: ansible_os_family == 'RedHat'