---
- name: "My First Playbook"
  hosts: ec2
  become_user: root
  become: yes

  tasks:
    - name: Create User
      user:
        name: george1
        home: /home/george1
        shell: /bin/bash

    - name: Change password
      user:
        name: george
        update_password: always
        password: "{{ newpassword|password_hash('sha512') }}"
