---
- name: "My First Playbook"
  hosts: ec2
  become_user: root
  become: yes
  vars:
    packages: [ftp, telnet, firewalld]

  tasks:
    - name: Install packages
      yum:
        name: "{{ packages }}"
        state: present
      tags: i-package

    - name: Start packages
      service:
        name: "{{ packages }}"
        state: started
      tags: s-package  
