---
- name: "My First Playbook"
  hosts: ec2
  become_user: root
  become: yes
  vars:
    users: [jerry1, jerry2]

  tasks:
    - name: Create user
      user:
        name: "{{ item }}"
      with_items: '{{ users }}'


