--- 
- hosts: ec2_instances
  become: true
  become_user: root
  tasks:
      - name: Fetch file 
        fetch:
          src: /etc/nginx/ssl/zoomusg104152023.key
          dest: /Users/tripurakant/9janssl