--- 
- hosts: ec2
  become: true
  become_user: root
  tasks:
      - name: Fetch file 
        fetch:
          src: /build/download-package.sh
          dest: /Users/tripurakant/Google Drive/My Drive/log-files