---
- hosts: ec2
  become: true
  become_user: root
  gather_facts: yes
  vars:
    distributions:
      - RedHat
      - Ubuntu
      - CentOS
  tasks:
    - name: "{{ distributions }} Installation when supported"
      yum:
        name: postfix
        state: absent
      when: ansible_distribution in distributions
