--- 
- hosts: ec2_instances
  become: true
  become_user: root
  tasks: 
        - name: User account creation
          user:
              name: monu1
              uid: 4045
              state: present
